//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int InternShipID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<System.DateTime> Start_Day { get; set; }
        public Nullable<System.DateTime> End_Day { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Student Student { get; set; }
    }
}
